
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.SQLOutput;
import javax.swing.JButton;
import javax.swing.JColorChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author k00253718
 */
public class TypingApplication extends javax.swing.JFrame
{

	private final Color keyboardJButtonColor = null;
//null sets the system default colour
	//https://stackoverflow.com/questions/1358398/how-to-get-jbutton-default-background-color


	private Color selectedButtonColor = Color.YELLOW;

	private final JButton[] keyJButtons = new JButton[KeyEvent.KEY_LAST + 1];

	Font font = new Font("Times New Roman", Font.PLAIN, 12);

	public TypingApplication()
	{
		initComponents();

		keyJButtons[KeyEvent.VK_DEAD_TILDE] = tildeJButton;
		keyJButtons[KeyEvent.VK_1] = one;
		keyJButtons[KeyEvent.VK_2] = two;
		keyJButtons[KeyEvent.VK_3] = three;
		keyJButtons[KeyEvent.VK_4] = four;
		keyJButtons[KeyEvent.VK_5] = five;
		keyJButtons[KeyEvent.VK_6] = six;
		keyJButtons[KeyEvent.VK_7] = seven;
		keyJButtons[KeyEvent.VK_8] = eight;
		keyJButtons[KeyEvent.VK_9] = nine;
		keyJButtons[KeyEvent.VK_0] = zero;
		keyJButtons[KeyEvent.VK_MINUS] = minus;
		keyJButtons[KeyEvent.VK_EQUALS] = plus;
		keyJButtons[KeyEvent.VK_BACK_SPACE] = backspace;

		keyJButtons[KeyEvent.VK_TAB] = tab;
		keyJButtons[KeyEvent.VK_Q] = q;
		keyJButtons[KeyEvent.VK_W] = w;
		keyJButtons[KeyEvent.VK_E] = e;
		keyJButtons[KeyEvent.VK_R] = r;
		keyJButtons[KeyEvent.VK_T] = t;
		keyJButtons[KeyEvent.VK_Y] = y;
		keyJButtons[KeyEvent.VK_U] = u;
		keyJButtons[KeyEvent.VK_I] = i;
		keyJButtons[KeyEvent.VK_O] = o;
		keyJButtons[KeyEvent.VK_P] = p;
		keyJButtons[KeyEvent.VK_OPEN_BRACKET] = openbracket;
		keyJButtons[KeyEvent.VK_CLOSE_BRACKET] = closedbracket;
		keyJButtons[KeyEvent.VK_BACK_SLASH] = Fslash;

		keyJButtons[KeyEvent.VK_CAPS_LOCK] = caps;
		keyJButtons[KeyEvent.VK_A] = a;
		keyJButtons[KeyEvent.VK_S] = s;
		keyJButtons[KeyEvent.VK_D] = d;
		keyJButtons[KeyEvent.VK_F] = f;
		keyJButtons[KeyEvent.VK_G] = g;
		keyJButtons[KeyEvent.VK_H] = h;
		keyJButtons[KeyEvent.VK_J] = j;
		keyJButtons[KeyEvent.VK_K] = k;
		keyJButtons[KeyEvent.VK_L] = l;
		keyJButtons[KeyEvent.VK_SEMICOLON] = semicolon;
		keyJButtons[KeyEvent.VK_QUOTE] = quote;
		keyJButtons[KeyEvent.VK_ENTER] = enter;

		keyJButtons[KeyEvent.VK_SHIFT] = shift;
		keyJButtons[KeyEvent.VK_Z] = z;
		keyJButtons[KeyEvent.VK_X] = x;
		keyJButtons[KeyEvent.VK_C] = c;
		keyJButtons[KeyEvent.VK_V] = v;
		keyJButtons[KeyEvent.VK_B] = b;
		keyJButtons[KeyEvent.VK_N] = n;
		keyJButtons[KeyEvent.VK_M] = m;
		keyJButtons[KeyEvent.VK_COMMA] = comma;
		keyJButtons[KeyEvent.VK_PERIOD] = dot;
		keyJButtons[KeyEvent.VK_SLASH] = questionmark;

		keyJButtons[KeyEvent.VK_UP] = upArrow;
		keyJButtons[KeyEvent.VK_DOWN] = downArrow;
		keyJButtons[KeyEvent.VK_LEFT] = leftArrow;
		keyJButtons[KeyEvent.VK_RIGHT] = rightArrow;
		keyJButtons[KeyEvent.VK_SPACE] = spacebar;

		keyJButtons[KeyEvent.VK_ESCAPE] = tildeJButton;
		

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        tildeJButton = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        one = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        tab = new javax.swing.JButton();
        q = new javax.swing.JButton();
        e = new javax.swing.JButton();
        w = new javax.swing.JButton();
        r = new javax.swing.JButton();
        u = new javax.swing.JButton();
        i = new javax.swing.JButton();
        o = new javax.swing.JButton();
        t = new javax.swing.JButton();
        p = new javax.swing.JButton();
        openbracket = new javax.swing.JButton();
        y = new javax.swing.JButton();
        Fslash = new javax.swing.JButton();
        closedbracket = new javax.swing.JButton();
        caps = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        d = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        semicolon = new javax.swing.JButton();
        quote = new javax.swing.JButton();
        shift = new javax.swing.JButton();
        z = new javax.swing.JButton();
        x = new javax.swing.JButton();
        c = new javax.swing.JButton();
        b = new javax.swing.JButton();
        v = new javax.swing.JButton();
        n = new javax.swing.JButton();
        m = new javax.swing.JButton();
        comma = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        questionmark = new javax.swing.JButton();
        upArrow = new javax.swing.JButton();
        leftArrow = new javax.swing.JButton();
        rightArrow = new javax.swing.JButton();
        downArrow = new javax.swing.JButton();
        spacebar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        buttoncolourmenuitem = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        textcolourmenuitem = new javax.swing.JMenuItem();
        buttoncolormenuitem = new javax.swing.JMenuItem();
        cancelmenuitemButton = new javax.swing.JMenuItem();
        italicstyleButton = new javax.swing.JMenu();
        stylemenu = new javax.swing.JMenu();
        boldcheckbox = new javax.swing.JCheckBoxMenuItem();
        italiccheckbox = new javax.swing.JCheckBoxMenuItem();
        size12radioButton = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        size16radioButton = new javax.swing.JRadioButtonMenuItem();
        size22radioButton = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("jCheckBoxMenuItem7");

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("jCheckBoxMenuItem8");

        jCheckBoxMenuItem9.setSelected(true);
        jCheckBoxMenuItem9.setText("jCheckBoxMenuItem9");

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("jCheckBoxMenuItem10");

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("jCheckBoxMenuItem11");

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("jCheckBoxMenuItem12");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("jRadioButtonMenuItem4");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem5.setText("jMenuItem5");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar7.add(jMenu14);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TYPING APPLICATION");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jta.setColumns(20);
        jta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jta.setRows(5);
        jta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 910, 180));

        tildeJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tildeJButton.setText("~");
        tildeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tildeJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tildeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 50));

        two.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        two.setText("2");
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 60, 50));

        three.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        three.setText("3");
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, 50));

        four.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        four.setText("4");
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, 50));

        one.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        one.setText("1");
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 50));

        five.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        five.setText("5");
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 60, 50));

        six.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        six.setText("6");
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 60, 50));

        seven.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seven.setText("7");
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 60, 50));

        eight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eight.setText("8");
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 60, 50));

        nine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nine.setText("9");
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 60, 50));

        minus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minus.setText("-");
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 60, 50));

        zero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zero.setText("0");
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 60, 50));

        backspace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backspace.setText("Backspace");
        getContentPane().add(backspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, 50));

        plus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 60, 50));

        tab.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tab.setText("Tab");
        tab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabActionPerformed(evt);
            }
        });
        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 50));

        q.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        q.setText("Q");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 60, 50));

        e.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        e.setText("E");
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 50));

        w.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        w.setText("W");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });
        getContentPane().add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 60, 50));

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r.setText("R");
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 60, 50));

        u.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u.setText("U");
        getContentPane().add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 60, 50));

        i.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        i.setText("I");
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 60, 50));

        o.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        o.setText("O");
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 60, 50));

        t.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t.setText("T");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 60, 50));

        p.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        p.setText("P");
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 60, 50));

        openbracket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        openbracket.setText("[");
        getContentPane().add(openbracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 60, 50));

        y.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        y.setText("Y");
        getContentPane().add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 60, 50));

        Fslash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fslash.setText("\\");
            Fslash.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    FslashActionPerformed(evt);
                }
            });
            getContentPane().add(Fslash, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 70, 50));

            closedbracket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            closedbracket.setText("]");
            getContentPane().add(closedbracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 60, 50));

            caps.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            caps.setText("Caps");
            getContentPane().add(caps, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, 50));

            a.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            a.setText("A");
            a.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    aActionPerformed(evt);
                }
            });
            getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 60, 50));

            s.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            s.setText("S");
            getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 60, 50));

            d.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            d.setText("D");
            getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, 50));

            f.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            f.setText("F");
            getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 60, 50));

            g.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            g.setText("G");
            getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 60, 50));

            h.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            h.setText("H");
            getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 60, 50));

            j.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            j.setText("J");
            getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 60, 50));

            k.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            k.setText("K");
            getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 60, 50));

            l.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            l.setText("L");
            getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 60, 50));

            enter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            enter.setText("Enter");
            getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 120, 50));

            semicolon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            semicolon.setText(":");
            semicolon.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    semicolonActionPerformed(evt);
                }
            });
            getContentPane().add(semicolon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 60, 50));

            quote.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            quote.setText("\"");
            getContentPane().add(quote, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 70, 50));

            shift.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            shift.setText("Shift");
            shift.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    shiftActionPerformed(evt);
                }
            });
            getContentPane().add(shift, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 110, 50));

            z.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            z.setText("Z");
            getContentPane().add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 60, 50));

            x.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            x.setText("X");
            getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 60, 50));

            c.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            c.setText("C");
            getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 60, 50));

            b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            b.setText("B");
            getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 60, 50));

            v.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            v.setText("V");
            getContentPane().add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 50));

            n.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            n.setText("N");
            getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 60, 50));

            m.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            m.setText("M");
            getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 60, 50));

            comma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            comma.setText(",");
            getContentPane().add(comma, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 60, 50));

            dot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            dot.setText(".");
            getContentPane().add(dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 60, 50));

            questionmark.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            questionmark.setText("?");
            getContentPane().add(questionmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 60, 50));

            upArrow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            upArrow.setText("^");
            getContentPane().add(upArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 60, 50));

            leftArrow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            leftArrow.setText("<");
            getContentPane().add(leftArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, 50));

            rightArrow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            rightArrow.setText(">");
            getContentPane().add(rightArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 60, 50));

            downArrow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            downArrow.setText("v");
            downArrow.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    downArrowActionPerformed(evt);
                }
            });
            getContentPane().add(downArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 60, 50));

            spacebar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            getContentPane().add(spacebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 358, 50));

            buttoncolourmenuitem.setText("Display");
            buttoncolourmenuitem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
            jMenuItem2.setText("Clear Text");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            buttoncolourmenuitem.add(jMenuItem2);
            buttoncolourmenuitem.add(jSeparator1);

            textcolourmenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
            textcolourmenuitem.setText("Text Colour");
            textcolourmenuitem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textcolourmenuitemActionPerformed(evt);
                }
            });
            buttoncolourmenuitem.add(textcolourmenuitem);

            buttoncolormenuitem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
            buttoncolormenuitem.setText("Button Colour");
            buttoncolormenuitem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buttoncolormenuitemActionPerformed(evt);
                }
            });
            buttoncolourmenuitem.add(buttoncolormenuitem);

            cancelmenuitemButton.setText("Cancel");
            cancelmenuitemButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cancelmenuitemButtonActionPerformed(evt);
                }
            });
            buttoncolourmenuitem.add(cancelmenuitemButton);

            jMenuBar1.add(buttoncolourmenuitem);

            italicstyleButton.setText("Format");
            italicstyleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

            stylemenu.setText("Style");

            boldcheckbox.setText("Bold");
            boldcheckbox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    boldcheckboxActionPerformed(evt);
                }
            });
            stylemenu.add(boldcheckbox);

            italiccheckbox.setText("Italic");
            italiccheckbox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    italiccheckboxActionPerformed(evt);
                }
            });
            stylemenu.add(italiccheckbox);

            italicstyleButton.add(stylemenu);

            size12radioButton.setText("Size");

            jRadioButtonMenuItem3.setSelected(true);
            jRadioButtonMenuItem3.setText("12");
            jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem3ActionPerformed(evt);
                }
            });
            size12radioButton.add(jRadioButtonMenuItem3);

            size16radioButton.setSelected(true);
            size16radioButton.setText("16");
            size16radioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    size16radioButtonActionPerformed(evt);
                }
            });
            size12radioButton.add(size16radioButton);

            size22radioButton.setSelected(true);
            size22radioButton.setText("20");
            size22radioButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    size22radioButtonActionPerformed(evt);
                }
            });
            size12radioButton.add(size22radioButton);

            jRadioButtonMenuItem6.setSelected(true);
            jRadioButtonMenuItem6.setText("22");
            jRadioButtonMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem6ActionPerformed(evt);
                }
            });
            size12radioButton.add(jRadioButtonMenuItem6);

            italicstyleButton.add(size12radioButton);

            jMenuBar1.add(italicstyleButton);

            setJMenuBar(jMenuBar1);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_plusActionPerformed

    private void downArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downArrowActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_downArrowActionPerformed

    private void tildeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tildeJButtonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_tildeJButtonActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_shiftActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_wActionPerformed

    private void textcolourmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcolourmenuitemActionPerformed
		Color selectedColor = JColorChooser.showDialog(this, "Select A Color", Color.pink);

		jta.setForeground(selectedColor);
// TODO add your handling code here:
    }//GEN-LAST:event_textcolourmenuitemActionPerformed

    private void jtaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaKeyPressed
		//
		//System.out.println ("key pressed"); 
		JButton button = keyJButtons[evt.getKeyCode()];
		Color theColor = button.getBackground();
		button.setBackground(selectedButtonColor);


    }//GEN-LAST:event_jtaKeyPressed

    private void jtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaKeyReleased
		JButton releasedButton = keyJButtons[evt.getKeyCode()];
		releasedButton.setBackground(keyboardJButtonColor);//System.out.println(" key released");        // TODO add your handling code here:
    }//GEN-LAST:event_jtaKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		jta.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void buttoncolormenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncolormenuitemActionPerformed
		selectedButtonColor = JColorChooser.showDialog(this, "Select A Color", Color.yellow);            // TODO add your handling code here:
    }//GEN-LAST:event_buttoncolormenuitemActionPerformed

    private void boldcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldcheckboxActionPerformed
		if (italiccheckbox.isSelected() && boldcheckbox.isSelected())
		{

			jta.setFont(font.deriveFont(Font.BOLD + Font.ITALIC));
		} else
		{
			if (!italiccheckbox.isSelected() && boldcheckbox.isSelected())
			{
				jta.setFont(font.deriveFont(Font.BOLD));
			} else
			{
				if (italiccheckbox.isSelected() && !boldcheckbox.isSelected())
				{
					jta.setFont(font.deriveFont(Font.ITALIC));
				} else
				{
					jta.setFont(font.deriveFont(Font.PLAIN));

				}
			}
		}
		//jta.setFont(font.deriveFont(Font.BOLD + Font.ITALIC());)

		// TODO add your handling code here:
    }//GEN-LAST:event_boldcheckboxActionPerformed

    private void tabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_tabActionPerformed

    private void FslashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FslashActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_FslashActionPerformed

    private void semicolonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semicolonActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_semicolonActionPerformed

    private void italiccheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italiccheckboxActionPerformed
		font = new Font("Times New Roman", Font.ITALIC, 16);

		if (italiccheckbox.isSelected() && boldcheckbox.isSelected())
		{

			jta.setFont(font.deriveFont(Font.BOLD + Font.ITALIC));
		} else
			if (!italiccheckbox.isSelected() && boldcheckbox.isSelected())
			{
				jta.setFont(font.deriveFont(Font.BOLD));
			} else
				if (italiccheckbox.isSelected() && !boldcheckbox.isSelected())
				{
					jta.setFont(font.deriveFont(Font.ITALIC));
				} else
				{
					jta.setFont(font.deriveFont(Font.PLAIN));

					jta.setFont(font);// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_italiccheckboxActionPerformed
	}
    private void size16radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size16radioButtonActionPerformed
		font = new Font("Times New Roman", Font.PLAIN, 16);
		jta.setFont(font);// TODO add your handling code here:
    }//GEN-LAST:event_size16radioButtonActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed

		if (stylemenu.isSelected() && italiccheckbox.isSelected())
		{
			font = new Font("Times New Roman", Font.BOLD + Font.ITALIC, 16);
			jta.setFont(font);// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed
        else
			if (!stylemenu.isSelected() && italiccheckbox.isSelected())
			{
				font = new Font("Times New Roman", Font.ITALIC, 16);
				jta.setFont(font);
			} else
			{
				if (stylemenu.isSelected() && !italiccheckbox.isSelected())
				{

					font = new Font("Times New Roman", Font.BOLD, 16);
					jta.setFont(font);
				} else
				{
					font = new Font("Times New Ronan", Font.PLAIN, 16);
					jta.setFont(font);
				}
			}
	}

    private void size22radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size22radioButtonActionPerformed
		font = new Font("Times New Roman", Font.PLAIN, 20);
		jta.setFont(font);// TODO add your handling code here:      
		// TODO add your handling code here:
		if (stylemenu.isSelected() && italiccheckbox.isSelected())
		{
			font = new Font("Times New Roman", Font.BOLD + Font.ITALIC, 20);
			jta.setFont(font);// TODO add your handling code here:        // TODO add your handling code here:
		} else
			if (!stylemenu.isSelected() && italiccheckbox.isSelected())
			{
				font = new Font("Times New Roman", Font.ITALIC, 20);
				jta.setFont(font);
			} else
				if (stylemenu.isSelected() && italiccheckbox.isSelected())
				{

					font = new Font("Times New Roman", Font.BOLD + Font.BOLD, 20);
					jta.setFont(font);
				} else
				{
					font = new Font("Times New Ronan", Font.PLAIN, 20);
					jta.setFont(font);
				}
    }//GEN-LAST:event_size22radioButtonActionPerformed

    private void jRadioButtonMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem6ActionPerformed

    private void cancelmenuitemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelmenuitemButtonActionPerformed
		jta.setText("");    //   cancelmenuitemButton.addActionListener();    
		//   if(E.getSource () ==cancelmenuitemButton)
//
		System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_cancelmenuitemButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(TypingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(TypingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(TypingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(TypingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new TypingApplication().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fslash;
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton backspace;
    private javax.swing.JCheckBoxMenuItem boldcheckbox;
    private javax.swing.JMenuItem buttoncolormenuitem;
    private javax.swing.JMenu buttoncolourmenuitem;
    private javax.swing.JButton c;
    private javax.swing.JMenuItem cancelmenuitemButton;
    private javax.swing.JButton caps;
    private javax.swing.JButton closedbracket;
    private javax.swing.JButton comma;
    private javax.swing.JButton d;
    private javax.swing.JButton dot;
    private javax.swing.JButton downArrow;
    private javax.swing.JButton e;
    private javax.swing.JButton eight;
    private javax.swing.JButton enter;
    private javax.swing.JButton f;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JCheckBoxMenuItem italiccheckbox;
    private javax.swing.JMenu italicstyleButton;
    private javax.swing.JButton j;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jta;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton leftArrow;
    private javax.swing.JButton m;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JButton minus;
    private javax.swing.JButton n;
    private javax.swing.JButton nine;
    private javax.swing.JButton o;
    private javax.swing.JButton one;
    private javax.swing.JButton openbracket;
    private javax.swing.JButton p;
    private javax.swing.JButton plus;
    private javax.swing.JButton q;
    private javax.swing.JButton questionmark;
    private javax.swing.JButton quote;
    private javax.swing.JButton r;
    private javax.swing.JButton rightArrow;
    private javax.swing.JButton s;
    private javax.swing.JButton semicolon;
    private javax.swing.JButton seven;
    private javax.swing.JButton shift;
    private javax.swing.JButton six;
    private javax.swing.JMenu size12radioButton;
    private javax.swing.JRadioButtonMenuItem size16radioButton;
    private javax.swing.JRadioButtonMenuItem size22radioButton;
    private javax.swing.JButton spacebar;
    private javax.swing.JMenu stylemenu;
    private javax.swing.JButton t;
    private javax.swing.JButton tab;
    private javax.swing.JMenuItem textcolourmenuitem;
    private javax.swing.JButton three;
    private javax.swing.JButton tildeJButton;
    private javax.swing.JButton two;
    private javax.swing.JButton u;
    private javax.swing.JButton upArrow;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
